services:
  nginx:
    depends_on:
      - wordpress
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress/.
    container_name: wordpress
    volumes:
      - ./web:/var/www/html
    networks:
      - inception
    env_file:
      - .env

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    networks:
      - inception
    env_file:
      - .env


networks:
  inception:
    driver: bridge
