services:
  nginx:
    depends_on:
      - wordpress
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped

  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress/.
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped


networks:
  inception:

volumes:
  mariadb:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ./web
      o: bind

