services:
  nginx:
    depends_on:
      - wordpress
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - /home/ekamada/data:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped

  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress/.
    container_name: wordpress
    volumes:
      - /home/ekamada/data:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - db_host
      - db_name
      - db_password
      - db_prefix
      - db_user
      - wp_admin_email
      - wp_admin_password
      - wp_author_email
      - wp_author_password
    restart: unless-stopped

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - db_host
      - db_name
      - db_password
      - db_prefix
      - db_user
    restart: unless-stopped



networks:
  inception:

secrets:
  db_host:
    file: ../secrets/db_host.txt
  db_name:
    file: ../secrets/db_name.txt
  db_password:
    file: ../secrets/db_password.txt
  db_prefix:
    file: ../secrets/db_prefix.txt
  db_user:
    file: ../secrets/db_user.txt
  wp_admin_email:
    file: ../secrets/wp_admin_email.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_author_email:
    file: ../secrets/wp_author_email.txt
  wp_author_password:
    file: ../secrets/wp_author_password.txt
