#!/bin/bash

mariadb -u$MYSQL_USER -p$MYSQL_PASSWORD -e "CREATE DATABASE $MYSQL_DATABASE"
mariadb -u$MYSQL_USER -p$MYSQL_PASSWORD -e "CREATE USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD'"
mariadb -u$MYSQL_USER -p$MYSQL_PASSWORD -e "GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'%'"
mariadb -u$MYSQL_USER -p$MYSQL_PASSWORD -e "FLUSH PRIVILEGES"
mysqld_safe

